default_config:

logger:
  default: info
  logs:
    custom_components.biedronka: debug

# Remote Python debugger (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
  start: true
  wait: true
